{
 "title": "Värmepump",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "heatpump_unit_on", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Läge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(heatpump_settings_mode) without(instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Effekt / Förbrukning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "w" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(heatpump_sensor_power_watt) without (instance)",
     "legendFormat": " "
    },
    {
     "expr": "sum(sum_over_time(heatpump_sensor_power_watt[$__range]) / (count_over_time(scrape_samples_scraped{job=\"husdata-exporter\"}[1m]) * 60) / 1000) without (instance)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Ute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_temperature_celsius{friendly_name=\"Indoor Unknown 02:00:00:36:a3:e2 Temperature\"}",
     "legendFormat": "Faktisk"
    },
    {
     "expr": "sum(heatpump_sensor_temperature_celsius{sensor=\"Ute\"}) without (instance)",
     "legendFormat": "Kompenserad"
    }
   ]
  },
  {
   "title": "Inne",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_temperature_celsius{friendly_name=\"Ngenic sensor Vardagsrum temperature\"}",
     "legendFormat": "Ngenic"
    },
    {
     "expr": "homeassistant_sensor_temperature_celsius{friendly_name=\"Indoor Temperature\"}",
     "legendFormat": "Netatmo"
    }
   ]
  },
  {
   "title": "Larm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "heatpump_alarm", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Varmvatten",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(heatpump_sensor_temperature_celsius{sensor=\"Varmvatten Laddning\"}) without (instance)",
     "legendFormat": "Laddning"
    }
   ]
  },
  {
   "title": "Gradminuter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(heatpump_degree_minutes_celsius)  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kompressor 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "st" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(heatpump_unit_starts_total{unit=\"Kompressor\"}[24h])",
     "legendFormat": "Starter"
    },
    {
     "expr": "increase(heatpump_unit_runtime_seconds_total{unit=\"Kompressor\"}[24h])",
     "legendFormat": "Drift"
    }
   ]
  },
  {
   "title": "Starter",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(heatpump_unit_on) by (unit)",
     "legendFormat": "{{unit}}"
    }
   ]
  },
  {
   "title": "Electricity price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyDKK" } },
   "targets": [
    {
     "columns": [
      { "selector": "startsAt", "text": "time", "type": "timestamp" },
      { "selector": "total", "text": "price", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "data.viewer.homes[0].currentSubscription.priceInfo.today",
     "source": "url",
     "type": "graphql",
     "url": "https://api.tibber.com/v1-beta/gql",
     "url_options": {
      "body_content_type": "application/json",
      "body_graphql_query": "{\n  viewer {\n    homes {\n      currentSubscription{\n        priceInfo{\n          today {\n            total\n            startsAt\n          }\n        }\n      }\n    }\n  }\n}",
      "body_type": "graphql",
      "data": "",
      "method": "POST"
     }
    },
    {
     "columns": [
      { "selector": "startsAt", "text": "time", "type": "timestamp" },
      { "selector": "total", "text": "price", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "data.viewer.homes[0].currentSubscription.priceInfo.tomorrow",
     "source": "url",
     "type": "graphql",
     "url": "https://api.tibber.com/v1-beta/gql",
     "url_options": {
      "body_content_type": "application/json",
      "body_graphql_query": "{\n  viewer {\n    homes {\n      currentSubscription{\n        priceInfo{\n          tomorrow {\n            total\n            startsAt\n          }\n        }\n      }\n    }\n  }\n}",
      "body_type": "graphql",
      "data": "",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Varmvatten",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(heatpump_sensor_temperature_celsius{sensor=\"Varmvatten Laddning\"})",
     "legendFormat": "Laddning"
    },
    {
     "expr": "sum(heatpump_sensor_temperature_celsius{sensor=\"Varmvatten Topp\"})",
     "legendFormat": "Topp"
    }
   ]
  },
  {
   "title": "Inne/Ute-temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_temperature_celsius{friendly_name=\"Ngenic sensor Vardagsrum temperature\"}",
     "legendFormat": "Inne"
    },
    {
     "expr": "homeassistant_sensor_temperature_celsius{friendly_name=\"Indoor Unknown 02:00:00:36:a3:e2 Temperature\"}",
     "legendFormat": "Ute"
    }
   ]
  },
  {
   "title": "Fram/Return-ledning",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum without (instance) (heatpump_sensor_temperature_celsius{sensor=\"Framledning\"})",
     "legendFormat": "Radiator"
    },
    {
     "expr": "sum without (instance) (heatpump_sensor_temperature_celsius{sensor=\"Framledning 2\"})",
     "legendFormat": "Golvvärme"
    },
    {
     "expr": "sum without (instance) (heatpump_sensor_temperature_celsius{sensor=\"Returledning\"})",
     "legendFormat": "Retur radiator"
    },
    {
     "expr": "sum without (instance) (heatpump_sensor_temperature_celsius{sensor=\"Returledning 2\"})",
     "legendFormat": "Retur golvvärme"
    },
    {
     "expr": "heatpump_heating_set_point_celsius",
     "legendFormat": "Börvärde"
    }
   ]
  },
  {
   "title": "Radiator DeltaT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum((heatpump_sensor_temperature_celsius{sensor=\"Framledning\"} - ignoring(sensor) heatpump_sensor_temperature_celsius{sensor=\"Returledning\"}))",
     "legendFormat": "DeltaT Radiator"
    },
    {
     "expr": "sum((heatpump_sensor_temperature_celsius{sensor=\"Framledning 2\"} - ignoring(sensor) heatpump_sensor_temperature_celsius{sensor=\"Returledning 2\"}))",
     "legendFormat": "DeltaT Golvvärme"
    }
   ]
  },
  {
   "title": "Gradminuter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(heatpump_degree_minutes_celsius) without (instance)",
     "legendFormat": "Radiator"
    }
   ]
  },
  {
   "title": "Hetgas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(heatpump_sensor_temperature_celsius{sensor=\"Hetgas\"}) without (instance)",
     "legendFormat": "Radiator"
    }
   ]
  }
 ]
}